version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
    - 6.3.3
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.1.1
    - 5.1.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.12.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.4
    - 11.2.6
  - dependency-name: react-test-renderer
    versions:
    - 17.0.2
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@babel/helper-define-map"
    versions:
    - 7.13.12
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.3
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.3
  - dependency-name: "@fortawesome/free-regular-svg-icons"
    versions:
    - 5.15.3
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.35
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
