plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: /Users/Dan/Code/react-vds/.yarn/releases/yarn-berry.js

packageExtensions:
  "sass-loader@*":
    optionalDependencies:
      node-sass: "*"
